[package]
name = "tmod-shell-extension"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
windows = { version = "0.52", features = ["implement", "Win32_System_Com", "Win32_Foundation"] }
